# Generated by Django 2.2 on 2021-04-26 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements_app', '0009_auto_20210426_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='ad_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='advertisements_app.AdvertisementType', verbose_name='рубрика'),
        ),
    ]
