# Generated by Django 3.2.5 on 2021-08-06 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shop_items', to='app_goods.shop'),
            preserve_default=False,
        ),
    ]
