# Generated by Django 3.2.5 on 2021-08-07 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0002_orderitem_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='status',
            field=models.CharField(choices=[('I', 'Initial'), ('S', 'Silver'), ('P', 'Platinum'), ('G', 'Gold')], default='Plain', max_length=10),
        ),
    ]
