# Generated by Django 2.2 on 2021-07-17 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_shop', '0002_auto_20210717_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='ru_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='category_ru'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ru_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='product_ru'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='app_shop.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
